[grpc]
connect_timeout = "30s"
request_timeout = "30s" 
max_message_size = 16777216  # 16MB - allows for 10MB updates and some headroom

use_tls = true

# HTTP2 flow control
http2_adaptive_window = true               # Enable for large and variable message sizes
http2_keep_alive_interval = "30s"          # Detect dead connections
initial_connection_window_size = 33554432  # 32MB window - match or exceed expected message sizes
initial_stream_window_size = 33554432      # 32MB per stream - same reason

# TCP tuning
tcp_nodelay = true     # Send pings immediately
tcp_keepalive = "60s"  # OS-level dead connection detection
buffer_size = 1024     # Raise buffer, as 64 might not be enough with bursts

[benchmark]
buffer_percentage = 0.1
latency_samples = 20